tasks:
  - name: Install Nextflow
    init: |
      cd /workspace; curl -s https://get.nextflow.io | bash
  - name: Prepare example
    init: |
      cd /workspace; mkdir genesets
      echo APAF1 BAD BAK1 BAX BCL2 BCL2A1 BCL2L1 BCL2L11 BID BIK CASP3 CASP7 CASP8 CASP9 HRK PMAIP1 PUMA BMF BCL2L2 CYCS MCL1 | tr ' ' '\n' > genesets/apoptosis.txt
      echo AKT1 AKT2 AKT3 CRKL IRS2 MTOR PIK3CA PIK3CG PIK3R1 PIK3R2 PTEN RICTOR RNF43 RPTOR TSC1 TSC2 | tr ' ' '\n' > genesets/pi3k.txt
      echo 184A1 AU565 BT20 BT474 BT549 CAL120 | tr ' ' '\n' > cl.txt
      echo 'params.drugs = ["A-1210477", "BJP-6-5-3", "senexin-B"]' > custom.config
  - name: Download the container
    init: |
      tag=$(grep contVers nextflow.config  | cut -f 3 -d ' ')
      eval "docker pull labsyspharm/brca-profiling:$tag"